/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DAO.PedidoDAO;
import Modelos.Pedido;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matteus
 */
public class FechamentoCaixa extends javax.swing.JInternalFrame {

    /**
     * Creates new form FechamentoCaixa
     */
    PedidoDAO dao;
    List<Pedido> pedidos;

    DefaultTableModel tmPedido = new DefaultTableModel(null, new String[]{
        "Cliente", "Valor", "Pedido", "Endereço"}) {
        boolean[] canEdit = new boolean[]{
            false, false, false, false
        };

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };

    public FechamentoCaixa() throws SQLException {
        super("Pesquisa de Pedidos");
        initComponents();
        jTabela.setAutoResizeMode(jTabela.AUTO_RESIZE_OFF);
        jTabela.getColumnModel().getColumn(0).setPreferredWidth(160);
        jTabela.getColumnModel().getColumn(1).setPreferredWidth(130);
        jTabela.getColumnModel().getColumn(2).setPreferredWidth(340);
        jTabela.getColumnModel().getColumn(3).setPreferredWidth(280);
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCabecalho = new javax.swing.JLabel();
        jLTotal = new javax.swing.JLabel();
        jBLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();

        setClosable(true);

        jLCabecalho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLCabecalho.setText("Fechamento de Caixa");

        jLTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLTotal.setText("Total:");

        jBLimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atualizar.png"))); // NOI18N
        jBLimpar.setText("Limpar Pedidos");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jTabela.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabela.setModel(tmPedido);
        jTabela.setRowHeight(23);
        jScrollPane1.setViewportView(jTabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBLimpar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCabecalho)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCabecalho)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLimpar)
                    .addComponent(jLTotal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        int pergunta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir todos os Pedidos?");
        if (pergunta == 0) {//clicou em sim
            try {
                dao = new PedidoDAO();
                dao.limpar();
                JOptionPane.showMessageDialog(null, "Caixa Finalizado Com Sucesso!");
                while (tmPedido.getRowCount() > 0) {
                    tmPedido.removeRow(0);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro: " + ex);
            }
        } else if (pergunta == 1) {//clicou em nao
        }
    }//GEN-LAST:event_jBLimparActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLimpar;
    private javax.swing.JLabel jLCabecalho;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    // End of variables declaration//GEN-END:variables

    private void populateFields() throws SQLException {
        dao = new PedidoDAO();
        pedidos = dao.listar();
        while (tmPedido.getRowCount() > 0) {
            tmPedido.removeRow(0);
        }
        Double total = .0;
        for (int i = 0; i < pedidos.size(); i++) {
            total += pedidos.get(i).getValor();
            tmPedido.addRow(new String[]{null, null, null, null});
            tmPedido.setValueAt(pedidos.get(i).getCliente(), i, 0);
            tmPedido.setValueAt(format(pedidos.get(i).getValor()), i, 1);
            tmPedido.setValueAt(pedidos.get(i).getPedido(), i, 2);
            tmPedido.setValueAt(pedidos.get(i).getEndereco(), i, 3);
        }
        jLTotal.setText("Total: " + format(total));
    }

    public static String format(double x) {
        return String.format("R$ %.2f", x);
    }
}
