/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DAO.FornecedorDAO;
import Modelos.Fornecedor;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author matteus
 */
public class PesquisaFornecedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form PesquisaFornecedores
     */
    FornecedorDAO dao = new FornecedorDAO();
    List<Fornecedor> fornecedores;

    DefaultTableModel tmFornecedor = new DefaultTableModel(null, new String[]{
        "Nome", "CNPJ", "Email", "Endereço"}) {
        boolean[] canEdit = new boolean[]{
            false, false, false, false
        };

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };

    public PesquisaFornecedores() throws ParseException {
        super("Pesquisa de Fornecedores");
        initComponents();
        jTabela.setAutoResizeMode(jTabela.AUTO_RESIZE_OFF);
        jTabela.getColumnModel().getColumn(0).setPreferredWidth(250);
        jTabela.getColumnModel().getColumn(1).setPreferredWidth(190);
        jTabela.getColumnModel().getColumn(2).setPreferredWidth(240);
        jTabela.getColumnModel().getColumn(3).setPreferredWidth(580);
        MaskFormatter maskCnpj = new MaskFormatter("##.###.###/####-##");
        maskCnpj.install(jFTCNPJ);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCabecalho = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jBLimpar = new javax.swing.JButton();
        jFTCNPJ = new javax.swing.JFormattedTextField();
        jLCNPJ = new javax.swing.JLabel();
        jBPesquisar = new javax.swing.JButton();

        setClosable(true);

        jLCabecalho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLCabecalho.setText("Pesquisa de Fornecedores");

        jLNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLNome.setText("Nome:");

        jTNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNomeKeyTyped(evt);
            }
        });

        jTabela.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabela.setModel(tmFornecedor);
        jTabela.setRowHeight(23);
        jTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabela);

        jBLimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/limpar.png"))); // NOI18N
        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jFTCNPJ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLCNPJ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLCNPJ.setText("CNPJ:");

        jBPesquisar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisar.png"))); // NOI18N
        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLCabecalho)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLNome)
                                .addGap(18, 18, 18)
                                .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBLimpar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCNPJ)
                        .addGap(18, 18, 18)
                        .addComponent(jFTCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBPesquisar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCabecalho)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNome)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCNPJ)
                    .addComponent(jFTCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jBLimpar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        jTNome.setText("");
        jFTCNPJ.setText("");
        while (tmFornecedor.getRowCount() > 0) {
            tmFornecedor.removeRow(0);
        }
        fornecedores = null;
        dao = new FornecedorDAO();
    }//GEN-LAST:event_jBLimparActionPerformed

    private void jTNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNomeKeyTyped
        try {
            fornecedores = dao.listar("%" + jTNome.getText() + "%");
            while (tmFornecedor.getRowCount() > 0) {
                tmFornecedor.removeRow(0);
            }

            String endereco;
            for (int i = 0; i < fornecedores.size(); i++) {
                tmFornecedor.addRow(new String[]{null, null, null, null});
                // rua, numero - Centro - Cruzeiro/SP. CEP: 1223123123
                endereco = fornecedores.get(i).getRua() + ", "
                        + fornecedores.get(i).getNum() + " - "
                        + fornecedores.get(i).getBairro() + " - "
                        + fornecedores.get(i).getCidade() + "/"
                        + fornecedores.get(i).getEstado() + ". CEP: "
                        + fornecedores.get(i).getCep();
                tmFornecedor.setValueAt(fornecedores.get(i).getNome(), i, 0);
                tmFornecedor.setValueAt(fornecedores.get(i).getCnpj(), i, 1);
                tmFornecedor.setValueAt(fornecedores.get(i).getEmail(), i, 2);
                tmFornecedor.setValueAt(endereco, i, 3);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex);
        }
    }//GEN-LAST:event_jTNomeKeyTyped

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        try {
            dao = new FornecedorDAO();
            fornecedores = dao.ListarCNPJ(jFTCNPJ.getText());
            while (tmFornecedor.getRowCount() > 0) {
                tmFornecedor.removeRow(0);
            }

            String endereco;
            for (int i = 0; i < fornecedores.size(); i++) {
                tmFornecedor.addRow(new String[]{null, null, null, null});
                endereco = fornecedores.get(i).getRua() + ", "
                        + fornecedores.get(i).getNum() + " - "
                        + fornecedores.get(i).getBairro() + " - "
                        + fornecedores.get(i).getCidade() + "/"
                        + fornecedores.get(i).getEstado() + ". CEP: "
                        + fornecedores.get(i).getCep();
                tmFornecedor.setValueAt(fornecedores.get(i).getNome(), i, 0);
                tmFornecedor.setValueAt(fornecedores.get(i).getCnpj(), i, 1);
                tmFornecedor.setValueAt(fornecedores.get(i).getEmail(), i, 2);
                tmFornecedor.setValueAt(endereco, i, 3);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex);
        }
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseClicked
        if (evt.getButton() != evt.BUTTON3 && evt.getClickCount() == 2) {
            int pergunta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir este Fornecedor?");
            if (pergunta == 0) {//clicou em sim
                try {
                    dao = new FornecedorDAO();
                    dao.remover(fornecedores.get(jTabela.getSelectedRow()).getId());
                    JOptionPane.showMessageDialog(null, "Fornecedor deletada com sucesso.");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro: " + ex);
                }
            } else if (pergunta == 1) {//clicou em nao
            }
        }
    }//GEN-LAST:event_jTabelaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JFormattedTextField jFTCNPJ;
    private javax.swing.JLabel jLCNPJ;
    private javax.swing.JLabel jLCabecalho;
    private javax.swing.JLabel jLNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTable jTabela;
    // End of variables declaration//GEN-END:variables
}
