CREATE DATABASE PETISCOS_LANCHES;
USE PETISCOS_LANCHES;

CREATE TABLE IF NOT EXISTS FORNECEDORES (
	FOR_ID SERIAL PRIMARY KEY,
	FOR_NOME VARCHAR (150),
	FOR_CNPJ VARCHAR (18),
	FOR_EMAIL VARCHAR (150),
	FOR_RUA VARCHAR (150),
	FOR_NUM VARCHAR (7),
	FOR_BAIRRO VARCHAR (60),
	FOR_CIDADE VARCHAR (100),
	FOR_ESTADO VARCHAR (2),
	FOR_CEP VARCHAR (9)
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
	PRO_ID SERIAL PRIMARY KEY,
	PRO_NOME VARCHAR (150),
	PRO_QUANTIDADE SMALLINT,
	PRO_VALIDADE DATE,
	PRO_FORNECEDOR INT,
	CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PRO_FORNECEDOR) REFERENCES FORNECEDORES (FOR_ID) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS LANCHES (
	LAN_ID SERIAL PRIMARY KEY,
	LAN_NOME VARCHAR (150),
	LAN_INGREDIENTES TEXT,
	LAN_VALOR DECIMAL(9,2)
);

CREATE TABLE IF NOT EXISTS PEDIDOS (
	PED_ID SERIAL PRIMARY KEY,
	PED_CLIENTE VARCHAR (150),
	PED_VALOR DECIMAL (9,2),
	PED_ENDERECO VARCHAR (250),
	PED_PEDIDO TEXT
);